//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using Definition;
    
    
    internal partial class FileServiceWrapper : ServiceBase<IFileServiceDefinition>, IFileService
    {
        
        public FileServiceWrapper(InfusionSoft.IInfusionSoftConfiguration configuration) : 
                base(configuration)
        {
        }
        
        public virtual object GetFile(int fileId)
        {
            return Invoke(d => d.GetFile(ApiKey, fileId));
        }
        
        public virtual object GetDownloadUrl(int fileId)
        {
            return Invoke(d => d.GetDownloadUrl(ApiKey, fileId));
        }
        
        public virtual object UploadFile(string fileName, string base64EncodedData, int contactId)
        {
            return Invoke(d => d.UploadFile(ApiKey, fileName, base64EncodedData, contactId));
        }
        
        public virtual object ReplaceFile(int fileId, string base64EncodedData)
        {
            return Invoke(d => d.ReplaceFile(ApiKey, fileId, base64EncodedData));
        }
        
        public virtual object RenameFile(int fileId, string fileName)
        {
            return Invoke(d => d.RenameFile(ApiKey, fileId, fileName));
        }
    }
}
