//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using Definition;
    
    
    internal partial class OrderServiceWrapper : ServiceBase<IOrderServiceDefinition>, IOrderService
    {
        
        public OrderServiceWrapper(InfusionSoft.IInfusionSoftConfiguration configuration) : 
                base(configuration)
        {
        }
        
        public virtual object PlaceOrder(int contactId, int creditCardId, int payPlanId, int[] productIds, int[] subscriptionPlanIds, bool processSpecials, string[] promoCodes)
        {
            return Invoke(d => d.PlaceOrder(ApiKey, contactId, creditCardId, payPlanId, productIds, subscriptionPlanIds, processSpecials, promoCodes));
        }
    }
}
