#region License

// Copyright (c) 2012, EventDay
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
// 
// Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using InfusionSoft.Definition;


namespace InfusionSoft
{
    
    
    internal partial class SearchServiceWrapper : ServiceBase<ISearchServiceDefinition>, ISearchService
    {
        
        public SearchServiceWrapper(InfusionSoft.IInfusionSoftConfiguration configuration, InfusionSoft.IMethodListenerProvider listenerProvider) : 
                base(configuration, listenerProvider)
        {
        }
        
        public virtual object GetAllReportColumns(int savedSearchId, int userId)
        {
            return Invoke(d => d.GetAllReportColumns(ApiKey, savedSearchId, userId));
        }
        
        public virtual object GetSavedSearchResultsAllFields(int savedSearchId, int userId, int pageNumber)
        {
            return Invoke(d => d.GetSavedSearchResultsAllFields(ApiKey, savedSearchId, userId, pageNumber));
        }
        
        public virtual object GetAvailableQuickSearches(int userId)
        {
            return Invoke(d => d.GetAvailableQuickSearches(ApiKey, userId));
        }
        
        public virtual object QuickSearch(int quickSearchType, int userId, int searchData, int page, int returnLimit)
        {
            return Invoke(d => d.QuickSearch(ApiKey, quickSearchType, userId, searchData, page, returnLimit));
        }
        
        public virtual object GetDefaultQuickSearch()
        {
            return Invoke(d => d.GetDefaultQuickSearch(ApiKey));
        }
    }
}
