//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IAffiliateService : InfusionSoft.IService
    {
        
        object AffClawbacks(int affiliateId, System.DateTime filterStartDate, System.DateTime filterEndDate);
        
        object AffCommissions(int affiliateId, System.DateTime filterStartDate, System.DateTime filterEndDate);
        
        object AffPayouts(int affiliateId, System.DateTime filterStartDate, System.DateTime filterEndDate);
        
        object AffRunningTotals(string[] affiliateIds);
        
        object AffSummary(int affiliateId, System.DateTime filterStartDate, System.DateTime filterEndDate);
    }
}
