#region License

// Copyright (c) 2012, EventDay
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
// 
// Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


namespace InfusionSoft
{
    
    
    public interface IContactService : InfusionSoft.IService
    {
        
        int Add(System.Collections.IDictionary data);
        
        bool AddToCampaign(int contactId, int campaignId);
        
        bool AddToGroup(int contactId, int campaignId);
        
        int GetNextCampaignStep(int contactId, int followUpSequenceId);
        
        InfusionSoft.Tables.Contact[] FindByEmail(string email, string[] selectedFields);
        
        InfusionSoft.Tables.Contact Load(int contactId, string[] selectedFields);
        
        bool PauseCampaign(int contactId, int sequenceId);
        
        bool RemoveFromCampaign(int contactId, int followUpSequenceId);
        
        bool RemoveFromGroup(int contactId, int tagId);
        
        bool ResumeCampaignForContact(int contactId, int seqId);
        
        int RescheduleCampaignStep(int[] contactIds, int sequenceStepId);
        
        InfusionSoft.Definition.RunActionSequenceResult[] RunActionSequence(int contactId, int actionSetId);
        
        int AddWithDupCheck(System.Collections.IDictionary data, string dupCheckType);
        
        int Update(int contactId, System.Collections.IDictionary data);
    }
}
