//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IDataService : InfusionSoft.IService
    {
        int Add(string table, System.Collections.IDictionary values);
        
        object Load(string table, int recordId, string[] wantedFields);
        
        int Update(string table, int id, object values);
        
        bool Delete(string table, int id);
        
        System.Collections.Generic.IEnumerable<object> FindByField(string table, int limit, int page, string fieldName, object fieldValue, string[] returnFields);
        
        System.Collections.Generic.IEnumerable<object> Query(string table, int limit, int page, System.Collections.IDictionary queryData, string[] selectedFields);
        
        int AddCustomField(string customFieldType, string displayName, string dataType, int headerId);
        
        int AuthenticateUser(string username, string passwordHash);
        
        string GetAppSetting(string module, string setting);
        
        string GetTemporaryKey(string username, string passwordHash);
        
        bool UpdateCustomField(int customFieldId, System.Collections.IDictionary values);
    }
}
