//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IFileService : InfusionSoft.IService
    {
        
        object GetFile(int fileId);
        
        object GetDownloadUrl(int fileId);
        
        object UploadFile(string fileName, string base64EncodedData, int contactId);
        
        object ReplaceFile(int fileId, string base64EncodedData);
        
        object RenameFile(int fileId, string fileName);
    }
}
