//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IProductService : InfusionSoft.IService
    {
        
        object GetInventory(int productId);
        
        object IncrementInventory(int productId);
        
        object DecrementInventory(int productId);
        
        object IncreaseInventory(int productId, int quantity);
        
        object DecreaseInventory(int productId, int quantity);
        
        object DeactivateCreditCard(int creditCardId);
    }
}
