//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using System;
    using System.Collections.Generic;
    
    
    public interface ISearchService : InfusionSoft.IService
    {
        
        object GetAllReportColumns(int savedSearchId, int userId);
        
        object GetSavedSearchResultsAllFields(int savedSearchId, int userId, int pageNumber);
        
        object GetAvailableQuickSearches(int userId);
        
        object QuickSearch(int quickSearchType, int userId, int searchData, int page, int returnLimit);
        
        object GetDefaultQuickSearch();
    }
}
