//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfusionSoft
{
    using System;
    using System.Collections.Generic;
    
    
    public interface IShippingService : InfusionSoft.IService
    {
        
        object GetAllShippingOptions();
        
        object GetFlatRateShippingOption(int optionId);
        
        object GetOrderTotalShippingOption(int optionId);
        
        object GetOrderTotalShippingRanges(int optionId);
        
        object GetProductShippingPricesForProductShippingOption(int id);
        
        object GetProductBasedShippingOption(int optionId);
        
        object GetOrderQuantityShippingOption(int optionId);
        
        object GetWeightBasedShippingOption(int optionId);
        
        object GetWeightBasedShippingRanges(int id);
        
        object GetUpsShippingOption(int optionId);
    }
}
